"""Generated code detection."""

from __future__ import annotations

from ...fs import read_file_safe, walk_files
from ..base import BaseDetector, DetectorContext, DetectorResult
from ..registry import DetectorRegistry


@DetectorRegistry.register
class GeneratedCodeDetector(BaseDetector):
    """Detect generated code directories, configs, and file markers."""

    name = "generic_generated_code"
    description = "Detects generated code that should not be manually edited"

    def detect(self, ctx: DetectorContext) -> DetectorResult:
        """Detect generated code locations."""
        result = DetectorResult()

        generated_dirs: list[str] = []
        codegen_configs: list[str] = []
        generated_patterns: list[str] = []
        marker_count = 0

        # Check for codegen config files
        config_files = {
            ".graphqlrc.yml": "GraphQL codegen",
            ".graphqlrc.json": "GraphQL codegen",
            "codegen.yml": "GraphQL codegen",
            "codegen.ts": "GraphQL codegen",
            "codegen.json": "GraphQL codegen",
            "buf.gen.yaml": "Protobuf (buf)",
            "buf.gen.yml": "Protobuf (buf)",
            "openapi-generator-cli.json": "OpenAPI codegen",
            "sqlc.yaml": "sqlc (SQL codegen)",
            "sqlc.yml": "sqlc (SQL codegen)",
        }
        for fname, label in config_files.items():
            if (ctx.repo_root / fname).is_file():
                codegen_configs.append(fname)

        # Check for known generated directories
        known_dirs = [
            "generated",
            "__generated__",
            "gen",
        ]
        for d in known_dirs:
            if (ctx.repo_root / d).is_dir():
                generated_dirs.append(d)

        # Check for Prisma client
        prisma_client = ctx.repo_root / "node_modules" / ".prisma" / "client"
        if prisma_client.is_dir():
            generated_dirs.append("node_modules/.prisma/client")

        # Check for generated file patterns by scanning source files
        gen_suffixes = {
            "_pb2.py": "Protobuf (Python)",
            ".pb.go": "Protobuf (Go)",
            "_pb2_grpc.py": "gRPC (Python)",
            ".generated.ts": "TypeScript codegen",
            ".generated.go": "Go codegen",
            ".gen.go": "Go codegen",
        }
        source_exts = {".py", ".go", ".ts", ".js", ".rs", ".java", ".tsx", ".jsx"}
        seen_patterns: set[str] = set()
        markers = ("@generated", "DO NOT EDIT", "Code generated by", "auto-generated", "This file is generated")

        for source_file in walk_files(ctx.repo_root, extensions=source_exts, max_files=500):
            fname = source_file.name

            # Check for generated file patterns
            for suffix, label in gen_suffixes.items():
                if fname.endswith(suffix) and suffix not in seen_patterns:
                    generated_patterns.append(f"*{suffix}")
                    seen_patterns.add(suffix)

            # Check first 5 lines for generation markers
            content = read_file_safe(source_file)
            if content:
                header = "\n".join(content.splitlines()[:5])
                for m in markers:
                    if m in header:
                        marker_count += 1
                        break

        if not generated_dirs and not codegen_configs and not generated_patterns and marker_count == 0:
            return result

        parts = []
        if generated_dirs:
            parts.append(f"{len(generated_dirs)} generated dirs")
        if codegen_configs:
            parts.append(f"{len(codegen_configs)} codegen configs")
        if generated_patterns:
            parts.append(f"patterns: {', '.join(generated_patterns[:3])}")
        if marker_count:
            parts.append(f"{marker_count} files with generation markers")

        description = f"Generated code detected: {'; '.join(parts)}."

        result.rules.append(self.make_rule(
            rule_id="generic.conventions.generated_code",
            category="structure",
            title="Generated code",
            description=description,
            confidence=0.85,
            language="generic",
            evidence=[],
            stats={
                "generated_dirs": generated_dirs,
                "codegen_configs": codegen_configs,
                "generated_file_patterns": generated_patterns,
                "marker_count": marker_count,
            },
        ))

        return result
