"""Tests for generated code detection."""
from __future__ import annotations

from pathlib import Path

from conventions.detectors.base import DetectorContext
from conventions.detectors.generic.generated_code import GeneratedCodeDetector


class TestGeneratedCodeDetection:
    """Tests for generated code detection."""

    def test_detect_codegen_configs(self, tmp_path: Path):
        """Detects codegen configuration files."""
        (tmp_path / "codegen.yml").write_text("generates:\n  ./src/generated:\n")
        (tmp_path / "buf.gen.yaml").write_text("version: v1\n")

        ctx = DetectorContext(
            repo_root=tmp_path,
            selected_languages=set(),
            max_files=100,
        )
        result = GeneratedCodeDetector().detect(ctx)

        rules = [r for r in result.rules if r.id == "generic.conventions.generated_code"]
        assert len(rules) == 1
        configs = rules[0].stats["codegen_configs"]
        assert "codegen.yml" in configs
        assert "buf.gen.yaml" in configs

    def test_detect_generated_directories(self, tmp_path: Path):
        """Detects known generated code directories."""
        (tmp_path / "generated").mkdir()
        (tmp_path / "generated" / "types.ts").write_text("")

        ctx = DetectorContext(
            repo_root=tmp_path,
            selected_languages=set(),
            max_files=100,
        )
        result = GeneratedCodeDetector().detect(ctx)

        rules = [r for r in result.rules if r.id == "generic.conventions.generated_code"]
        assert len(rules) == 1
        assert "generated" in rules[0].stats["generated_dirs"]

    def test_detect_generated_markers(self, tmp_path: Path):
        """Detects files with generation markers in headers."""
        src = tmp_path / "src"
        src.mkdir()
        (src / "types.py").write_text(
            "# Code generated by protoc-gen-python. DO NOT EDIT.\n"
            "class MyMessage:\n"
            "    pass\n"
        )
        (src / "normal.py").write_text(
            "# Normal file\n"
            "def hello():\n"
            "    pass\n"
        )

        ctx = DetectorContext(
            repo_root=tmp_path,
            selected_languages=set(),
            max_files=200,
        )
        result = GeneratedCodeDetector().detect(ctx)

        rules = [r for r in result.rules if r.id == "generic.conventions.generated_code"]
        assert len(rules) == 1
        assert rules[0].stats["marker_count"] >= 1

    def test_no_generated_code(self, tmp_path: Path):
        """No generated code emits no rule."""
        (tmp_path / "app.py").write_text("def main():\n    pass\n")

        ctx = DetectorContext(
            repo_root=tmp_path,
            selected_languages=set(),
            max_files=100,
        )
        result = GeneratedCodeDetector().detect(ctx)

        rules = [r for r in result.rules if r.id == "generic.conventions.generated_code"]
        assert len(rules) == 0
